---
- name: Create native debug build directory
  file:
    path: ~/qemu/build
    state: directory
    mode: 0755

- name: Configure QEMU in debug mode
  shell:
    chdir: ~/qemu/build
    cmd: ../configure --enable-debug --target-list=x86_64-softmmu

- name: Make
  shell:
    chdir: ~/qemu/build
    cmd: make -j4
