---
- name: Update apt package list
  become: yes  # Equivalent to running the command with 'sudo'
  apt:
    update_cache: yes
- name: Install required packages
  become: yes
  apt:
    name:
      - git
      - libglib2.0-dev
      - libfdt-dev
      - libpixman-1-dev
      - zlib1g-dev
      - ninja-build
      - flex
      - bison
      - python3-pip
      - python3-venv
      - python3-sphinx
      - qemu-kvm
      - libcap-ng-dev
      - libcurl4-gnutls-dev
      - libgtk-3-dev
      - libsdl2-dev
      - libnfs-dev
      - libiscsi-dev
    state: present
- name: Install python modules
  become: yes
  pip:
    name:
      - ninja
      - sphinx-rtd-theme
    state: present
    executable: pip3 # Use pip3 for python3
