---
- name: Update apt package list
  become: yes  # Equivalent to running the command with 'sudo'
  apt:
    update_cache: yes
- name: Install required packages
  become: yes  # Equivalent to running the command with 'sudo'
  apt:
    name:
      - xfce4
      - xfce4-goodies
      - xrdp
    state: present
- name: Enable xrdp
  systemd:
    name: xrdp
    enabled: yes
- name: Start xrdp
  systemd:
    name: xrdp
    state: started
